### ISSUE TITLE
Negative cash on hand from transitory chock

### ISSUE THREAD

**Issue by AskerNC** [NumEconCopenhagen/AdvMacroHet#1]
My question is regarding the third exercise from lecture 1, where a transitory chock is introduced in the model, giving the following budget constraint: 

$a_{t}=(1+r)a_{t-1}+wz_{t}-c_{t}+\xi_{t}$

given that $\xi_{t}$ is gaussian it can potentially be very negative and offset all income and savings in a given period giving negative cash-on-hand right?
I'm a bit unsure of how we deal with this, both directly in the code and theoretically.
Theoretically, do we just have a model where each period some fraction of the agents endure negative consumption even though the utility function is not really defined in this space? 
If there is a tail-end risk of 0-consumption and infinitely negative utility how does that affect the expected utility in next period?
Implementation wise I ended up choosing a small std of $\xi$ and the number of gauss hermite grid low enough so I never looked at shocks there were more negative than the lowest possible income. But this feels very hacky. (My implementation is in the Exercises folder of my fork: https://github.com/AskerNC/AdvMacroHet ) 

I feel like I might be missing something here. Hope you can help.

Best regards and thanks in advance,
Asker

**Comment by JeppeDruedahl** [comment]
Great question!

Your hacky solution is the best possible. 

A better question is to introduce a multiplicative log-normal transitory shock instead. I have introduced this is my updated code.

Best,
 Jeppe
