### ISSUE TITLE
Potential oversigt in figures.py code

### ISSUE THREAD

**Issue by Goldfield1** [NumEconCopenhagen/AdvMacroHet#10]
Figures overwrite each other when trying to save impulse responses using $\texttt{GEModelTools.figures.showIRFS}$?

https://github.com/NumEconCopenhagen/GEModelTools/blob/fc6a4aa8330f83ac8c24991b54f321a1a2c77217/GEModelTools/figures.py#L127

Maybe you add an f-string that accounts for the typename?

**Comment by JeppeDruedahl** [comment]
I don't quite get the problem. Your can change the `filename` each time you call `GEModelTools.figures.showIRFs`.
