### ISSUE TITLE
Assignment 3 - should we discuss calibration

### ISSUE THREAD

**Issue by jacoropke** [NumEconCopenhagen/AdvMacroHet#11]
Hi Jeppe,
This is not really related to the code so perhaps the wrong place to ask this question. 

In the assignment, does the part about step-step explanation of analysis include stuff like parameter calibration and how we would solve the model if we had to?

Best,
Jacob

**Comment by JeppeDruedahl** [comment]
Hi

Not necessarily. If you think the choice of a specific parameter will be important perhaps discuss this. If your model imply a special challenge in solving it perhaps mention that.

Best,
 Jeppe
