### ISSUE TITLE
Maximum point in the grid over assets a being a max point multiplied with the wage.

### ISSUE THREAD

**Issue by jacoropke** [NumEconCopenhagen/AdvMacroHet#2]
Hi Jeppe

Why is it that the maximum point for the a-grid is written as: par.w*par.a_max and not just par._a_max?

Best,
Jacob

**Comment by JeppeDruedahl** [comment]
Hi

Good question! w is basically a scale parameter here, if it doubles so does c and a. Therefore I would often also like to double the maximum value in my grid for a. 

However, this is not completely true, when there is non-zero borrowing limit (as this is not scaled by w). I should therefore either remove the scaling with w or scale the borrowing limit by w, i.e. a >= w*b.


Best,
 Jeppe
