### ISSUE TITLE
Possible typos in assignment

### ISSUE THREAD

**Issue by jacoropke** [NumEconCopenhagen/AdvMacroHet#3]
Hi Jeppe

While this may just be me misunderstanding matters, I noticed some weird stuff in the assignment. 

1) In the maximization problem of the household, It is written as if the household only maximizes over their consumption choice.
2) In the section about handling the liquidity constraint: $c_t$ is set as 
$$c_t = (1+r_t) a_{t-1}+w_t l^{\*}_t \zeta_i z_t - c^{\*}_t$$

Should the $c^{\*}_t$ not be omitted such that we satistfy the FOC for labor and then uses the budget constraint(while consuming all savings) to compute consumption residually.

**Comment by JeppeDruedahl** [comment]
You are totally right. The max should be over $c_t$ and $\ell_t$, and in the section on handling the liquidity constraint, consumption should be set to imply zero savings given the budget constraint. The pdf has been updated.
