### ISSUE TITLE
Zeta in factor in EGM household problem assignment #1

### ISSUE THREAD

**Issue by fkj242** [NumEconCopenhagen/AdvMacroHet#4]
Hi,

I wondered whether there might be a zeta missing in the numerator of the factor tilde(w)z/phi in eq. 8 of the assignment. Is that right? I haven't gone through the math in detail but intuitively I would've thought fixed heterogeneity in productivity should be accounted for there too.

I may v well have missed something though!

**Comment by JeppeDruedahl** [comment]
Should this is a mistake. The pdf has been updated.
