### ISSUE TITLE
G in goods market?

### ISSUE THREAD

**Issue by Goldfield1** [NumEconCopenhagen/AdvMacroHet#5]
Hi,

Maybe I remember my micro badly, or I've made a mistake in my model equations, but solving the model gives me a "K_clearing" and "L_clearing" of 0, but a "C_clearing" of 0.3 - which lead me to conclude that government consumption was missing from the market clearing equation for the goods market, i.e. that it should be:

$$ Y_t = C_t + I_t + G_t  $$

This makes sense to me intuitively, however, is this a mistake?

**Comment by JeppeDruedahl** [comment]
Yes, you are correct.
