### ISSUE TITLE
Path dependancy in the solution

### ISSUE THREAD

**Issue by jacoropke** [NumEconCopenhagen/AdvMacroHet#6]
Hi Jeppe

Some of us seems to have path dependancy in our model solution. That is - using different initial guesses result in different equilibria. 

Should we see this as evidence of a code mistake? If not - do we simply choose one equilibrium for display in the assignment?

**Comment by JeppeDruedahl** [comment]
It surprsises me if there are multiple stationary equilibria. But I can not be sure that it is not the case. It is fully fine if you just document your results in your answer.
