### ISSUE TITLE
Assignment #2: lags and leads in the block code

### ISSUE THREAD

**Issue by AntonSteino** [NumEconCopenhagen/AdvMacroHet#8]
I seem to have a problem getting the block code to run properly. I have solved for the steady state, and that part is working, but running the model.test_path() command gives results that are very different from the steady state values (although they should be nearly identical).

I have tried to replace all lag() and lead() routines in the block-code by their respective ss. values (e.g. ss.q instead of lag(ini.q,q)). These values should be the same, considering that we are modelling the steady state only. Doing this helps! 

So I guess, I have a problem getting the lag() and lead() routines to work properly. I use the exact same form for the routines as in the GEModelToolsNotebooks HANK block file, i.e.

lag(ini.var,var) for lags
lead(var,ss.var) for leads

Can anyone see what I'm doing wrong here?

**Comment by JeppeDruedahl** [comment]
I understand that you have solved it yourselves :)
