### ISSUE TITLE
Different methods of solving leading to slightly different solutions

### ISSUE THREAD

**Issue by jacoropke** [NumEconCopenhagen/AdvMacroHet#9]
In the assignment I tried a few different ways of solving for the transition path. 

I stumbled upon an issue that puzzled me a bit. 

I used four targets(model can be solved with less, but this was a test) which was:
1. Asset Market clearing
2. NKPC
3. Taylor Rule
4. Government budget constraint

How I wrote the government budget constraint matters for the solution. I tried:
1. $q_t(B_t - \delta B_{t-1}) = B_{t-1} + G_t + \chi_t - \tau_t Y_t$
2. $q_t = (B_{t-1} + G_t + \chi_t - \tau_t Y_t) /(B_t - \delta B_{t-1})$

With the first option, the linear approximation is fairly close to the non-linear path. That is not the case with the second option. I assume it is because dividing with something close to zero is bad idea numerically. 

As a final note, when I solved the model with only two targets (NKPC and asset market clearing), the linear approximation was almost identical to the non-linear path.  In all cases, all marking clearing conditions were satisfied and the zero-shock(giving sequence of steady values) seems to pass, but the non-linear path was slightly different between them.  

Is the above just an issue of numerical precision?

I am unsure whether I should link the assignment code as this is part of the exam. 

Best,
Jacob

**Comment by JeppeDruedahl** [comment]
_Sorry for the late reply, my automatic alerts seems to have not worked._

In my code the linear and non-linear solutions are very similar. Choose the specification, where you get this. Then I will look into the potential problems you raise.
